BuySmart/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BuySmart.DAL;
using BuySmart.Models;
using BuySmart.ViewModels;

namespace BuySmart.Controllers
{
    public class AddressController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public IEnumerable<Address> GetAddresses(AddressSearchModel searchModel)
        {
            var result = unitOfWork.AddressRepository.Get(includeProperties: "Shop");

            if (searchModel != null)
            {
                if (!string.IsNullOrEmpty(searchModel.City))
                    result = result.Where(x => x.City.Contains(searchModel.City));
                if (!string.IsNullOrEmpty(searchModel.Street))
                    result = result.Where(x => x.Street.Contains(searchModel.Street));
                if (!string.IsNullOrEmpty(searchModel.ShopName))
                    result = result.Where(x => x.Shop.ShopName.Contains(searchModel.ShopName));
                if (searchModel.ShopType.HasValue)
                    result = result.Where(x => x.Shop.ShopType.Equals(searchModel.ShopType));
            }
            return result;
        }

        private void PopulateShopsDropDownList(object selectedShop = null)
        {
            var shopQuery = unitOfWork.ShopRepository.Get(
                orderBy: q => q.OrderBy(d => d.ShopId));
            ViewBag.ShopID = new SelectList(shopQuery, "ShopId", "ShopName", selectedShop);
        }

        // GET: Address
        public ViewResult Index(string sortOrder, AddressSearchModel searchModel, string currentFilterCity, string currentFilterStreet,
            string currentFilterShopName, ShopType? currentFilterShopType, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.CitySortParm = sortOrder == "city_asc" ? "city_desc" : "city_asc";
            ViewBag.StreetSortParm = sortOrder == "street_asc" ? "street_desc" : "street_asc";
            ViewBag.ShopNameSortParm = sortOrder == "shopName_asc" ? "shopName_desc" : "shopName_asc";
            ViewBag.ShopTypeSortParm = sortOrder == "shopType_asc" ? "shopType_desc" : "shopType_asc";

            if ((searchModel.City != null) || (searchModel.Street != null)
                || (searchModel.ShopName != null) || (searchModel.ShopType != null))
            {
                page = 1;
            }
            else
            {
                searchModel.City = currentFilterCity;
                searchModel.Street = currentFilterStreet;
                searchModel.ShopName = currentFilterShopName;
                searchModel.ShopType = currentFilterShopType;
            }

            var addresses = GetAddresses(searchModel);

            ViewBag.CurrentFilterCity = searchModel.City;
            ViewBag.CurrentFilterStreet = searchModel.Street;
            ViewBag.CurrentFilterShopName = searchModel.ShopName;
            ViewBag.CurrentFilterShopType = searchModel.ShopType;

            switch (sortOrder)
            {
                case "id_desc":
                    addresses = addresses.OrderByDescending(s => s.AddressId);
                    break;
                case "city_desc":
                    addresses = addresses.OrderByDescending(s => s.City);
                    break;
                case "city_asc":
                    addresses = addresses.OrderBy(s => s.City);
                    break;
                case "street_desc":
                    addresses = addresses.OrderByDescending(s => s.Street);
                    break;
                case "street_asc":
                    addresses = addresses.OrderBy(s => s.Street);
                    break;
                case "shopName_desc":
                    addresses = addresses.OrderByDescending(s => s.Shop.ShopName);
                    break;
                case "shopName_asc":
                    addresses = addresses.OrderBy(s => s.Shop.ShopName);
                    break;
                case "shopType_desc":
                    addresses = addresses.OrderByDescending(s => s.Shop.ShopType.ToString());
                    break;
                case "shopType_asc":
                    addresses = addresses.OrderBy(s => s.Shop.ShopType.ToString());
                    break;
                default:
                    addresses = addresses.OrderBy(s => s.AddressId);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            AddressIndexModel addressIndexModel = new AddressIndexModel(addresses, pageNumber, pageSize, currentFilterShopType);
            return View(addressIndexModel);
        }

        // GET: Address/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = unitOfWork.AddressRepository.GetById(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }
        
        // GET: Address/Create
        public ActionResult Create()
        {
            PopulateShopsDropDownList();
            return View();
        }

        // POST: Address/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShopId, Country, City, Street")]Address address)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.AddressRepository.Insert(address);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
                PopulateShopsDropDownList(address.ShopId);
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");
            }
            return View(address);
        }
      
        // GET: Address/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = unitOfWork.AddressRepository.GetById(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            PopulateShopsDropDownList(address.ShopId);
            return View(address);
        }

        // POST: Address/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var addressToUpdate = unitOfWork.AddressRepository.GetById(id);
            if (TryUpdateModel(addressToUpdate, "",
               new string[] { "ShopId", "Country", "City", "Street" }))
            {
                try
                {
                    unitOfWork.Save();
                    PopulateShopsDropDownList(addressToUpdate.ShopId);
                    return RedirectToAction("Index");
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");
                }
            }
            return View(addressToUpdate);
        }

        // GET: Address/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Usuwanie zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.";
            }
            Address address = unitOfWork.AddressRepository.GetById(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: Address/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Address address = unitOfWork.AddressRepository.GetById(id);
                unitOfWork.AddressRepository.Delete(address);
                unitOfWork.Save();
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BuySmart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Styles/css")

    <!-- Custom Fonts -->
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("BuySmart", "Index", "Home", null, new { @class = "navbar-brand topnav" })
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Kalkulator zakupowy", "SelectCriteria", "PurchasingCalculator")</li>
                <li>@Html.ActionLink("Wystąpienia produktów", "Index", "ProductOccurence")</li>
                <li>@Html.ActionLink("Produkty", "Index", "Product")</li>
                <li>@Html.ActionLink("Sklepy", "Index", "Shop")</li>
                <li>@Html.ActionLink("Adresy", "Index", "Address")</li>
                <li>@Html.ActionLink("Oferta", "Offer", "Home")</li>
                <li>@Html.ActionLink("O projekcie", "About", "Home")</li>
                <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</nav>

@RenderBody()

<div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>BuySmart</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="https://bitbucket.org/mateo1990/buysmart/" class="btn btn-default btn-lg"><i class="fa fa-bitbucket fa-fw"></i> <span class="network-name">BitBucket</span></a>
                        </li>
                        <li>
                            <a href="http://www.facebook.com/" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a href="https://plus.google.com/?hl=pl/" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline">
                    <li>
                        @Html.ActionLink("Strona główna", "Index", "Home")
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        @Html.ActionLink("Oferta", "Offer", "Home")
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        @Html.ActionLink("O projekcie", "About", "Home")
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                    <li>
                        @Html.ActionLink("Kontakt", "Contact", "Home")
                    </li>
                </ul>
                <p class="copyright text-muted small">Copyright &copy; BuySmart Mateusz Pucek 2015-2017. All Rights Reserved</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>