BuySmart/Models/ProductOccurence.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BuySmart.Models
{
    public class ProductOccurence
    {
        [Key]
        public int ProductOccurenceId { get; set; }
        public int ProductId { get; set; }
        public int ShopId { get; set; }

        [Range(0, 1000, ErrorMessage = "Cena produktu jest wymagana i musi mieścić się w przedziale od 0 do 1000 PLN")]
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal ProductPrice { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Data zakupu produktu jest wymagana")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ProductBuyDate { get; set; }

        public bool IsPromotional { get; set; }

        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}

BuySmart/Controllers/ProductOccurenceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BuySmart.DAL;
using BuySmart.Models;
using BuySmart.ViewModels;

namespace BuySmart.Controllers
{
    public class ProductOccurenceController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        private void PopulateProductsDropDownList(object selectedProduct = null)
        {
            var productQuery = unitOfWork.ProductRepository.Get(
                orderBy: q => q.OrderBy(d => d.ProductId));
            ViewBag.ProductID = new SelectList(productQuery, "ProductId", "ProductDescription", selectedProduct);
        }

        private void PopulateShopsDropDownList(object selectedShop = null)
        {
            var shopQuery = unitOfWork.ShopRepository.Get(
                orderBy: q => q.OrderBy(d => d.ShopId));
            ViewBag.ShopID = new SelectList(shopQuery, "ShopId", "ShopName", selectedShop);
        }

        public IEnumerable<ProductOccurence> GetProductOccurences(ProductOccurenceSearchModel searchModel)
        {
            var result = unitOfWork.ProductOccurenceRepository.Get(includeProperties: "Product,Shop");
            if (searchModel != null)
            {
                if (!string.IsNullOrEmpty(searchModel.Description))
                    result = result.Where(x => x.Product.ProductDescription.Contains(searchModel.Description));
                if (!string.IsNullOrEmpty(searchModel.ShopName))
                    result = result.Where(x => x.Shop.ShopName.Contains(searchModel.ShopName));
                if (searchModel.PriceFrom.HasValue)
                    result = result.Where(x => x.ProductPrice >= searchModel.PriceFrom);
                if (searchModel.PriceTo.HasValue)
                    result = result.Where(x => x.ProductPrice <= searchModel.PriceTo);
                if (searchModel.BuyDateFrom.HasValue)
                    result = result.Where(x => x.ProductBuyDate >= searchModel.BuyDateFrom);
                if (searchModel.BuyDateTo.HasValue)
                    result = result.Where(x => x.ProductBuyDate <= searchModel.BuyDateTo);
                if (searchModel.IsPromotional == true)
                    result = result.Where(x => x.IsPromotional == true);
            }
            return result;
        }

        // GET: ProductOccurence
        public ViewResult Index(string sortOrder, ProductOccurenceSearchModel searchModel, 
            string currentFilterDescription, string currentFilterShopName, decimal? currentFilterPriceFrom, decimal? currentFilterPriceTo,
            DateTime? currentFilterBuyDateFrom, DateTime? currentFilterBuyDateTo, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.ProductSortParm = sortOrder == "product_asc" ? "product_desc" : "product_asc";
            ViewBag.ShopSortParm = sortOrder == "shop_asc" ? "shop_desc" : "shop_asc";
            ViewBag.PriceSortParm = sortOrder == "price_asc" ? "price_desc" : "price_asc";
            ViewBag.BuyDateSortParm = sortOrder == "buyDate_asc" ? "buyDate_desc" : "buyDate_asc";

            if ((searchModel.Description != null) || (searchModel.ShopName != null)
                || (searchModel.PriceFrom != null) || (searchModel.PriceTo != null)
                || (searchModel.BuyDateFrom != null) || (searchModel.BuyDateTo != null))
            {
                page = 1;
            }
            else
            {
                searchModel.Description = currentFilterDescription;
                searchModel.ShopName = currentFilterShopName;
                searchModel.PriceFrom = currentFilterPriceFrom;
                searchModel.PriceTo = currentFilterPriceTo;
                searchModel.BuyDateFrom = currentFilterBuyDateFrom;
                searchModel.BuyDateTo = currentFilterBuyDateTo;
            }

            var productOccurences = GetProductOccurences(searchModel);

            ViewBag.CurrentFilterDescription = searchModel.Description;
            ViewBag.CurrentFilterShopName = searchModel.ShopName;
            ViewBag.CurrentFilterPriceFrom = searchModel.PriceFrom;
            ViewBag.CurrentFilterPriceTo = searchModel.PriceTo;
            ViewBag.CurrentFilterBuyDateFrom = String.Format("{0:yyyy-MM-dd}", searchModel.BuyDateFrom);
            ViewBag.CurrentFilterBuyDateTo = String.Format("{0:yyyy-MM-dd}", searchModel.BuyDateTo);

            switch (sortOrder)
            {
                case "id_desc":
                    productOccurences = productOccurences.OrderByDescending(s => s.ProductOccurenceId);
                    break;
                case "product_desc":
                    productOccurences = productOccurences.OrderByDescending(s => s.Product.ProductDescription);
                    break;
                case "product_asc":
                    productOccurences = productOccurences.OrderBy(s => s.Product.ProductDescription);
                    break;
                case "shop_desc":
                    productOccurences = productOccurences.OrderByDescending(s => s.Shop.ShopName);
                    break;
                case "shop_asc":
                    productOccurences = productOccurences.OrderBy(s => s.Shop.ShopName);
                    break;
                case "price_desc":
                    productOccurences = productOccurences.OrderByDescending(s => s.ProductPrice);
                    break;
                case "price_asc":
                    productOccurences = productOccurences.OrderBy(s => s.ProductPrice);
                    break;
                case "buyDate_desc":
                    productOccurences = productOccurences.OrderByDescending(s => s.ProductBuyDate);
                    break;
                case "buyDate_asc":
                    productOccurences = productOccurences.OrderBy(s => s.ProductBuyDate);
                    break;
                default:
                    productOccurences = productOccurences.OrderBy(s => s.ProductOccurenceId);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ProductOccurenceIndexModel productOccurenceIndexModel = new ProductOccurenceIndexModel(productOccurences, pageNumber, pageSize,
                currentFilterPriceFrom, currentFilterPriceTo, currentFilterBuyDateFrom, currentFilterBuyDateTo);
            return View(productOccurenceIndexModel);
        }

        // GET: ProductOccurence/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductOccurence productOccurence = unitOfWork.ProductOccurenceRepository.GetById(id);

            if (productOccurence == null)
            {
                return HttpNotFound();
            }
            return View(productOccurence);
        }

        // GET: ProductOccurence/Create
        public ActionResult Create()
        {
            PopulateProductsDropDownList();
            PopulateShopsDropDownList();
            return View();
        }

        // POST: ProductOccurence/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ShopId,ProductPrice,ProductBuyDate,IsPromotional")]ProductOccurence productOccurence)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.ProductOccurenceRepository.Insert(productOccurence);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
                PopulateProductsDropDownList(productOccurence.ProductId);
                PopulateShopsDropDownList(productOccurence.ShopId);
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");
            }
            return View(productOccurence);
        }

        // GET: ProductOccurence/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductOccurence productOccurence = unitOfWork.ProductOccurenceRepository.GetById(id);
            if (productOccurence == null)
            {
                return HttpNotFound();
            }
            PopulateProductsDropDownList(productOccurence.ProductId);
            PopulateShopsDropDownList(productOccurence.ShopId);
            return View(productOccurence);
        }

        // POST: ProductOccurence/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productOccurenceToUpdate = unitOfWork.ProductOccurenceRepository.GetById(id);
            PopulateProductsDropDownList(productOccurenceToUpdate.ProductId);
            PopulateShopsDropDownList(productOccurenceToUpdate.ShopId);
            if (TryUpdateModel(productOccurenceToUpdate, "",
               new string[] { "ProductId", "ShopId", "ProductPrice", "ProductBuyDate", "IsPromotional" }))
            {
                try
                {
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");

BuySmart/Views/ProductOccurence/Create.cshtml
@model BuySmart.Models.ProductOccurence

<link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-3.1.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/DatePicker/DatePicker.js")"></script>

@{
    ViewBag.Title = "Dodaj wystąpienie produktu";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Dodaj wystąpienie produktu</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductId, "Produkt", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ShopId, "Sklep", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ShopId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ShopId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductPrice, "Cena", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductBuyDate, "Data zakupu",  htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductBuyDate, new { htmlAttributes = new { @class = "form-control date-picker" } })
                            @Html.ValidationMessageFor(model => model.ProductBuyDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsPromotional, "Czy jest w promocji?", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsPromotional)
                                @Html.ValidationMessageFor(model => model.IsPromotional, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Utwórz" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Powrót do listy", "Index")
            </div>
        </div>
    </div>
</div>

BuySmart/Views/ProductOccurence/Delete.cshtml
@model BuySmart.Models.ProductOccurence

@{
    ViewBag.Title = "Delete product occurence";
}
<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Delete product occurence</h2>
            <p class="error">@ViewBag.ErrorMessage</p>
            <h3>Are you sure you want to delete this product occurence?</h3>
            <div>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Product description
                    </dt>
                    <dd>
                        <a href="@Url.Action("FetchProductOccurences", "Product", new { id = Model.ProductId })">
                            @Html.DisplayFor(modelItem => Model.Product.ProductDescription)
                        </a>
                    </dd>
                    <dt>
                        Shop name
                    </dt>

                    <dd>
                        <a href="@Url.Action("FetchProductOccurences", "Shop", new { id = Model.ShopId })">
                            @Html.DisplayFor(modelItem => Model.Shop.ShopName)
                        </a>
                    </dd>

                    <dt>
                        Price (PLN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProductPrice)
                    </dd>

                    <dt>
                        Buy date
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProductBuyDate)
                    </dd>

                    <dt>
                        Is promotional?
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsPromotional)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BuySmart/Views/ProductOccurence/Details.cshtml
@model BuySmart.Models.ProductOccurence

@{
    ViewBag.Title = "Details of product occurence";
}
<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Details of product occurence with ID=@Model.ProductOccurenceId</h2>

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Product description
                    </dt>
                    <dd>
                        <a href="@Url.Action("FetchProductOccurences", "Product", new { id = Model.ProductId })">
                            @Html.DisplayFor(modelItem => Model.Product.ProductDescription)
                        </a>
                    </dd>
                    <dt>
                        Shop name
                    </dt>

                    <dd>
                        <a href="@Url.Action("FetchProductOccurences", "Shop", new { id = Model.ShopId })">
                            @Html.DisplayFor(modelItem => Model.Shop.ShopName)
                        </a>
                    </dd>

                    <dt>
                        Price (PLN)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProductPrice)
                    </dd>

                    <dt>
                        Buy date
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProductBuyDate)
                    </dd>

                    <dt>
                        Is promotional?
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsPromotional)
                    </dd>

                </dl>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.ProductOccurenceId }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </div>
</div>

BuySmart/Views/ProductOccurence/Index.cshtml
@model BuySmart.ViewModels.ProductOccurenceIndexModel
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-3.1.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/DatePicker/DatePicker.js")"></script>

@{
    ViewBag.Title = "Wystąpienia produktów";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">

            <h2>Wystąpienia produktów</h2>

            <p>
                @Html.ActionLink("Dodaj nowe", "Create")
            </p>
            @using (Html.BeginForm("Index", "ProductOccurence", FormMethod.Get))
            {
                <table style="width: 60%; border-spacing: 30px;">
                    <tr>
                        <td>
                            Produkt <br />
                            @Html.TextBox("Description", ViewBag.CurrentFilterDescription as string) <br/>
                            Sklep <br />
                            @Html.TextBox("ShopName", ViewBag.CurrentFilterShopName as string)
                        </td>
                        <td>
                            Cena od <br />
                            @Html.EditorFor(model => model.PriceFrom)<br/>
                            Cena do <br />
                            @Html.EditorFor(m => m.PriceTo)
                        </td>
                        <td>
                            Data od
                            @Html.TextBox("BuyDateFrom", ViewBag.CurrentFilterBuyDateFrom as string, new { @class = "form-control date-picker" })
                            Data do
                            @Html.TextBox("BuyDateTo", ViewBag.CurrentFilterBuyDateTo as string, new { @class = "form-control date-picker" })
                        </td>
                    </tr>
                </table> 
                <p>
                    <input type="submit" value="Szukaj" />
                </p>

            }
            <table class="table custom-table">
                <tr>
                    <th>
                        @Html.ActionLink("ID", "Index", new
                        {
                            sortOrder = ViewBag.IDSortParm,
                            currentFilterDescription = ViewBag.CurrentFilterDescription,
                            currentFilterShopName = ViewBag.CurrentFilterShopName,
                            currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
                            currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
                            currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
                            currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
                            currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
                        })
                    </th>
                    <th>
                        Zdjęcie
                    </th>
                    <th>
                        @Html.ActionLink("Produkt", "Index", new {
                            sortOrder = ViewBag.ProductSortParm,
                            currentFilterDescription = ViewBag.CurrentFilterDescription,
                            currentFilterShopName = ViewBag.CurrentFilterShopName,
                            currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
                            currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
                            currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
                            currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
                            currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
                        })
                    </th>
                    <th>
                        @Html.ActionLink("Sklep", "Index", new {
                            sortOrder = ViewBag.ShopSortParm,
                            currentFilterDescription = ViewBag.CurrentFilterDescription,
                            currentFilterShopName = ViewBag.CurrentFilterShopName,
                            currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
                            currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
                            currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
                            currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
                            currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
                        })
                    </th>
                    <th>
                        @Html.ActionLink("Cena (PLN)", "Index", new {
                            sortOrder = ViewBag.PriceSortParm,
                            currentFilterDescription = ViewBag.CurrentFilterDescription,
                            currentFilterShopName = ViewBag.CurrentFilterShopName,
                            currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
                            currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
                            currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
                            currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
                            currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
                        })
                    </th>
                    <th>
                        @Html.ActionLink("Data zakupu", "Index", new {
                            sortOrder = ViewBag.BuyDateSortParm,
                            currentFilterDescription = ViewBag.CurrentFilterDescription,
                            currentFilterShopName = ViewBag.CurrentFilterShopName,
                            currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
                            currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
                            currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
                            currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
                            currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
                        })
                    </th>
                    <th>
                        Czy jest w promocji?
                    </th>
                    <th>
                        Akcje
                    </th>
                </tr>

                @foreach (var item in Model.ProductOccurences)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductOccurenceId)
                        </td>
                        <td>
                            @if (item.Product.Photo != null)
                            {
                                string imageBase64 = Convert.ToBase64String(item.Product.Photo.Content);
                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                <img src="@imageSrc" width="100" />
                            }
                        </td>
                        <td>
                            <a href="@Url.Action("FetchProductOccurences", "Product", new { id = item.ProductId })">
                                @Html.DisplayFor(modelItem => item.Product.ProductDescription)
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("FetchProductOccurences", "Shop", new { id = item.ShopId })">
                                @Html.DisplayFor(modelItem => item.Shop.ShopName)
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductBuyDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsPromotional)
                        </td>
                        <td>
                            @Html.ActionLink("Edytuj", "Edit", new { id = item.ProductOccurenceId }) |
                            @Html.ActionLink("Szczegóły", "Details", new { id = item.ProductOccurenceId }) |
                            @Html.ActionLink("Usuń", "Delete", new { id = item.ProductOccurenceId })
                        </td>
                    </tr>
                }
            </table>
            <br />
            Page @(Model.ProductOccurences.PageCount < Model.ProductOccurences.PageNumber ? 0 : Model.ProductOccurences.PageNumber) of @Model.ProductOccurences.PageCount

            @Html.PagedListPager(Model.ProductOccurences, page => Url.Action("Index", new
       {
           page,
           sortOrder = ViewBag.CurrentSort,
           currentFilterDescription = ViewBag.CurrentFilterDescription,
           currentFilterShopName = ViewBag.CurrentFilterShopName,
           currentFilterPriceFrom = ViewBag.CurrentFilterPriceFrom,
           currentFilterPriceTo = ViewBag.CurrentFilterPriceTo,
           currentFilterBuyDateFrom = ViewBag.CurrentFilterBuyDateFrom,
           currentFilterBuyDateTo = ViewBag.CurrentFilterBuyDateTo,
           currentFilterIsPromotional = ViewBag.CurrentFilterIsPromotional
       }))
        </div>
    </div>
</div>