BuySmart/Models/Product.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace BuySmart.Models
{
    public enum UnitOfMeasure
    {
        Item,
        Kilogram,
        Liter,
    }

    public class Product
    {
        public Product()
        {
            ProductOccurences = new List<ProductOccurence>();
        }

        [Key]
        public int ProductId { get; set; }
        public int ProductPhotoId { get; set; }

        public UnitOfMeasure? UnitOfMeasure { get; set; }
        [Required(ErrorMessage = "Opis produktu jest wymagany")]
        public string ProductDescription { get; set; }

        public virtual ProductPhoto Photo { get; set; }
        public virtual ICollection<ProductOccurence> ProductOccurences { get; set; }
    }

}

BuySmart/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BuySmart.DAL;
using BuySmart.Models;
using BuySmart.ViewModels;

namespace BuySmart.Controllers
{
    public class ProductController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public IEnumerable<Product> GetProducts(ProductSearchModel searchModel)
        {
            var result = unitOfWork.ProductRepository.Get(includeProperties: "Photo,ProductOccurences");

            if (searchModel != null)
            {
                if (!string.IsNullOrEmpty(searchModel.Description))
                    result = result.Where(x => x.ProductDescription.Contains(searchModel.Description));
                if (searchModel.UnitOfMeasure.HasValue)
                    result = result.Where(x => x.UnitOfMeasure.Equals(searchModel.UnitOfMeasure));
            }
            return result;
        }

        // GET: Product
        public ViewResult Index(string sortOrder, ProductSearchModel searchModel, string currentFilterDescription,
            UnitOfMeasure? currentFilterUnitOfMeasure, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.DescriptionSortParm = sortOrder == "description_asc" ? "description_desc" : "description_asc";
            ViewBag.UnitOfMeasureSortParm = sortOrder == "unitOfMeasure_asc" ? "unitOfMeasure_desc" : "unitOfMeasure_asc";

            if ((searchModel.Description != null) || (searchModel.UnitOfMeasure != null))
            {
                page = 1;
            }
            else
            {
                searchModel.Description = currentFilterDescription;
                searchModel.UnitOfMeasure = currentFilterUnitOfMeasure;
            }

            var products = GetProducts(searchModel);

            ViewBag.CurrentFilterDescription = searchModel.Description;
            ViewBag.CurrentFilterUnitOfMeasure = searchModel.UnitOfMeasure;

            switch (sortOrder)
            {
                case "id_desc":
                    products = products.OrderByDescending(s => s.ProductId);
                    break;
                case "description_desc":
                    products = products.OrderByDescending(s => s.ProductDescription);
                    break;
                case "description_asc":
                    products = products.OrderBy(s => s.ProductDescription);
                    break;
                case "unitOfMeasure_desc":
                    products = products.OrderByDescending(s => s.UnitOfMeasure);
                    break;
                case "unitOfMeasure_asc":
                    products = products.OrderBy(s => s.UnitOfMeasure);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductId);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ProductIndexModel productIndexModel = new ProductIndexModel(products, pageNumber, pageSize, currentFilterUnitOfMeasure);
            return View(productIndexModel);
        }

        public ViewResult FetchProductOccurences(int id)
        {
            var products = unitOfWork.ProductOccurenceRepository.Get(p => p.ProductId == id, includeProperties: "Product,Shop");
            ViewBag.ProductDescription = unitOfWork.ProductRepository.GetById(id).ProductDescription;
            return View(products.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UnitOfMeasure,ProductDescription")]Product product, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        var avatar = new ProductPhoto
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        product.Photo = avatar;
                    }
                    unitOfWork.ProductRepository.Insert(product);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productToUpdate = unitOfWork.ProductRepository.GetById(id);
            if (TryUpdateModel(productToUpdate, "",
               new string[] { "UnitOfMeasure", "ProductDescription" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (productToUpdate.Photo != null)
                        {
                            unitOfWork.ProductPhotoRepository.Delete(productToUpdate.Photo);
                        }
                        var avatar = new ProductPhoto
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            avatar.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        productToUpdate.Photo = avatar;
                    }
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
                catch (DataException)
                {
                    ModelState.AddModelError("", "Zapisanie zmian zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.");
                }
            }
            return View(productToUpdate);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Usuwanie zakończyło się niepowodzeniem. Spróbuj później, a jeśli problem będzie dalej występował, skontaktuj się z administratorem.";
            }
            Product product = unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Product product = unitOfWork.ProductRepository.GetById(id);
                if (product.Photo != null)
                {
                    ProductPhoto productPhoto = unitOfWork.ProductPhotoRepository.GetById(product.ProductId);
                    unitOfWork.ProductPhotoRepository.Delete(productPhoto.ProductPhotoId);
                }
                unitOfWork.ProductRepository.Delete(id);
                unitOfWork.Save();
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BuySmart/Views/Product/Create.cshtml
@model BuySmart.Models.Product

@{
    ViewBag.Title = "Create product";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Create product</h2>

            @using (Html.BeginForm("Create", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.UnitOfMeasure, "Unit of measure", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.UnitOfMeasure, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UnitOfMeasure, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Photo", new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="Photo" name="upload" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

BuySmart/Views/Product/Delete.cshtml
@model BuySmart.Models.Product

@{
    ViewBag.Title = "Delete product";
}
<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Delete product</h2>
            <p class="error">@ViewBag.ErrorMessage</p>
            <h3>Are you sure you want to delete this product?</h3>
            <div>
                <hr />
                <dl class="dl-horizontal">

                    <dt>
                        Product description
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ProductDescription)
                    </dd>

                    <dt>
                        Unit of measure
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UnitOfMeasure)
                    </dd>

                    <dt>
                        Product occurences
                    </dt>

                    <dd>
                        @Html.ActionLink("Show", "FetchProductOccurences", new { id = Model.ProductId })
                    </dd>
                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BuySmart/Views/Product/Details.cshtml
@model BuySmart.Models.Product

@{
    ViewBag.Title = "Details of product";
}
<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Details of product with ID=@Model.ProductId</h2>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    Photo
                </dt>
                <dd>
                    @if (Model.Photo != null)
                    {
                        string imageBase64 = Convert.ToBase64String(Model.Photo.Content);
                        string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                        <img src="@imageSrc" width="350" />
                    }
                    else
                    {
                        <p>No image</p>
                    }
                </dd>

                <dt>
                    Product description
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ProductDescription)
                </dd>

                <dt>
                    Unit of measure
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UnitOfMeasure)
                </dd>

                <dt>
                    Product occurences
                </dt>

                <dd>
                    @Html.ActionLink("Show", "FetchProductOccurences", new { id = Model.ProductId })
                </dd>
            </dl>

            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
            </div>
        </div>
    </div>

BuySmart/Views/Product/Edit.cshtml
@model BuySmart.Models.Product

@{
    ViewBag.Title = "Edit product";
}
<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Edit product</h2>

            @using (Html.BeginForm("Edit", "Product", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ProductId)

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UnitOfMeasure, "Unit of measure", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EnumDropDownListFor(model => model.UnitOfMeasure, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UnitOfMeasure, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                   
                    <div class="form-group">
                        <span class="control-label col-md-2"><strong>Current photo</strong></span>
                        <div class="col-md-10">
                        @if (Model.Photo != null)
                        {
                            string imageBase64 = Convert.ToBase64String(Model.Photo.Content);
                            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                            <img src="@imageSrc" width="350" />
                        }
                        else
                        {
                            <p>No image</p>
                        }
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Upload photo", new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="Photo" name="upload" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

BuySmart/Views/Product/FetchProductOccurences.cshtml
@model IEnumerable<BuySmart.Models.ProductOccurence>

@{
    ViewBag.Title = "Product occurences";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>
                Product occurences of @ViewBag.ProductDescription
            </h2>

            <p></p>
            <table class="table custom-table">
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Shop name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Buy date
                    </th>
                    <th>
                        Is promotional?
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>

                @{int i = 1;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <span>@i</span>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Shop.ShopName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductBuyDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsPromotional)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "ProductOccurence", new { id = item.ProductOccurenceId }, null) |
                            @Html.ActionLink("Details", "Details", "ProductOccurence", new { id = item.ProductOccurenceId }, null) |
                            @Html.ActionLink("Delete", "Delete", "ProductOccurence", new { id = item.ProductOccurenceId }, null)
                        </td>
                    </tr>
                    i++;
                }
            </table>
            <div>
                @Html.ActionLink("Back to product list", "Index", "Product")
            </div>

            <div>
                @Html.ActionLink("Back to product occurences list", "Index", "ProductOccurence")
            </div>
        </div>
    </div>
</div>

BuySmart/Views/Product/Index.cshtml
@model BuySmart.ViewModels.ProductIndexModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Products";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Products</h2>

            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
            @using (Html.BeginForm("Index", "Product", FormMethod.Get))
            {
                <p>
                    Description:
                    @Html.TextBox("Description", ViewBag.CurrentFilterDescription as string)
                    Unit of measure:
                    @Html.EnumDropDownListFor(m => m.UnitOfMeasure, "Select")
                </p>
                <p>
                    <input type="submit" value="Search" />
                </p>

            }
            <table class="table custom-table">
                <tr>
                    <th>
                        @Html.ActionLink("ID", "Index", new
                   {
                       sortOrder = ViewBag.IDSortParm,
                       currentFilterDescription = ViewBag.CurrentFilterDescription,
                       currentFilterUnitOfMeasure = ViewBag.CurrentFilterUnitOfMeasure
                   })
                    </th>
                    <th>
                        Photo
                    </th>
                    <th>
                        @Html.ActionLink("Description", "Index", new
                   {
                       sortOrder = ViewBag.DescriptionSortParm,
                       currentFilterDescription = ViewBag.CurrentFilterDescription,
                       currentFilterUnitOfMeasure = ViewBag.CurrentFilterUnitOfMeasure
                   })
                    </th>
                    <th>
                        @Html.ActionLink("Unit of measure", "Index", new
                   {
                       sortOrder = ViewBag.UnitOfMeasureSortParm,
                       currentFilterDescription = ViewBag.CurrentFilterDescription,
                       currentFilterUnitOfMeasure = ViewBag.CurrentFilterUnitOfMeasure
                   })
                    </th>
                    <th>
                        Product occurences
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>

                @foreach (var item in Model.Products)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductId)
                        </td>
                        <td>
                            @if (item.Photo != null)
                            {
                                string imageBase64 = Convert.ToBase64String(item.Photo.Content);
                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                <img src="@imageSrc" width="150" />
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UnitOfMeasure)
                        </td>
                        <td>
                            @Html.ActionLink("Show", "FetchProductOccurences", new { id = item.ProductId })
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ProductId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ProductId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ProductId })
                        </td>
                    </tr>
                }

            </table>
            <br />
            Page @(Model.Products.PageCount < Model.Products.PageNumber ? 0 : Model.Products.PageNumber) of @Model.Products.PageCount

            @Html.PagedListPager(Model.Products, page => Url.Action("Index", new
       {
           page,
           sortOrder = ViewBag.CurrentSort,
           currentFilterDescription = ViewBag.CurrentFilterDescription,
           currentFilterUnitOfMeasure = ViewBag.CurrentFilterUnitOfMeasure
       }))
        </div>
    </div>
</div>