BuySmart/ViewModels/PurchasingCalculator/AverageSalaryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class AverageSalaryModel
    {
        public int Year { get; set; }
        public decimal Salary { get; set; }

        public AverageSalaryModel(int year)
        {
            Year = year;
            Salary = GetAverageSalary(year);
        }

        public decimal GetAverageSalary(int year)
        {
            switch (year)
            {
                case 2017:
                    return 4257.79M;
                case 2016:
                    return 4055.04M;
                case 2015:
                    return 3899.78M;
                case 2014:
                    return 3783.46M;
                case 2013:
                    return 3650.06M;
                default:
                    return 0;
            }
        }

    }
}

BuySmart/ViewModels/PurchasingCalculator/InflationByProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuySmart.Models;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class InflationByProductModel
    {
        public PurchasingCalculatorProductModel Product { get; set; }
        public decimal? Inflation { get; set; }

        public InflationByProductModel(PurchasingCalculatorProductModel product, decimal? inflation)
        {
            Product = product;
            Inflation = inflation;
        }
    }
}

BuySmart/ViewModels/PurchasingCalculator/InflationByShopModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuySmart.Models;
using BuySmart.ViewModels;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class InflationByShopModel
    {
        public ShoppingBasketModel Shop { get; set; }
        public decimal? Inflation { get; set; }

        public InflationByShopModel(ShoppingBasketModel shop, decimal? inflation)
        {
            Shop = shop;
            Inflation = inflation;
        }
    }
}

BuySmart/ViewModels/PurchasingCalculator/InflationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class InflationModel
    {
        public List<InflationByShopModel> ShopInflation { get; set; }
        public List<InflationByProductModel> ProductInflation { get; set; }
        public decimal? AverageInflation { get; set; }

        public InflationModel(List<InflationByShopModel> shopInflation, List<InflationByProductModel> productInflation,
            decimal? averageInflation)
        {
            ShopInflation = shopInflation;
            ProductInflation = productInflation;
            AverageInflation = averageInflation;
        }
    }
}

BuySmart/ViewModels/PurchasingCalculator/PurchasingCalculatorCriteriaModel.cs
using System;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class PurchasingCalculatorCriteriaModel
    {
        public int? AmountOfProductFields { get; set; }
        public string Localization { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
    }
}

BuySmart/ViewModels/PurchasingCalculator/PurchasingCalculatorInputModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class PurchasingCalculatorInputModel
    {
        public PurchasingCalculatorCriteriaModel Criteria { get; set; }
        public PurchasingCalculatorSelectedProductValuesModel[] SelectedProductsValues { get; set; }
        public IEnumerable<SelectListItem> AllProducts { get; set; }
    }
}

BuySmart/ViewModels/PurchasingCalculator/PurchasingCalculatorProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuySmart.Models;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class PurchasingCalculatorProductModel
    {

        public PurchasingCalculatorProductModel(Product product, decimal? amount)
        {
            Product = product;
            Amount = amount;
        }

        public Product Product { get; set; }
        public decimal? Amount { get; set; }
    }
}

BuySmart/ViewModels/PurchasingCalculator/PurchasingCalculatorSelectedProductValuesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuySmart.Models;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class PurchasingCalculatorSelectedProductValuesModel : Product
    {
        public int SelectedProductId { get; set; }
        public int SelectedAmount { get; set; }
    }
}

BuySmart/ViewModels/PurchasingCalculator/PurchasingPowerModel.cs
namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class PurchasingPowerModel
    {
        public PurchasingPowerModel(AverageSalaryModel averageSalaryModel, decimal? purchasingPowerValue)
        {
            AverageSalaryModel = averageSalaryModel;
            PurchasingPowerValue = purchasingPowerValue;
        }

        public AverageSalaryModel AverageSalaryModel { get; set; }
        public decimal? PurchasingPowerValue { get; set; }
    }
}

BuySmart/ViewModels/PurchasingCalculator/ShoppingBasketModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BuySmart.Models;

namespace BuySmart.ViewModels.PurchasingCalculator
{
    public class ShoppingBasketModel
    {
        public ShoppingBasketModel(Shop shop, decimal? basketPrice)
        {
            Shop = shop;
            BasketPrice = basketPrice;
        }

        public Shop Shop { get; set; }
        public decimal? BasketPrice { get; set; }
        public bool ProductNotFound { get; set; }
    }
}

BuySmart/Controllers/PurchasingCalculatorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BuySmart.DAL;
using BuySmart.Models;
using BuySmart.ViewModels.PurchasingCalculator;

namespace BuySmart.Controllers
{
    public class PurchasingCalculatorController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        [HttpGet]
        public ActionResult SelectCriteria()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SelectCriteria(PurchasingCalculatorCriteriaModel criteriaModel)
        {
            TempData["currentCriteria"] = criteriaModel;
            if ((criteriaModel.Localization == null) || (criteriaModel.DateFrom == null) ||
                (criteriaModel.DateTo == null))
                return View("ErrorCriteria");
            return RedirectToAction("SelectProducts", criteriaModel);
        }

        [HttpGet]
        public ActionResult SelectProducts()
        {
            var allProducts = unitOfWork.ProductRepository.Get(includeProperties: "Photo,ProductOccurences");
            var newList = new List<object>();
            foreach (var item in allProducts)
                newList.Add(new
                {
                    ProductId = item.ProductId,
                    ProductDescription = item.UnitOfMeasure + ": " + item.ProductDescription
                });
            var inputModel = new PurchasingCalculatorInputModel()
            {
                AllProducts = new SelectList(newList, "ProductId", "ProductDescription"),
                Criteria = TempData["currentCriteria"] as PurchasingCalculatorCriteriaModel
            };
            TempData["currentCriteria"] = inputModel.Criteria;
            return View(inputModel);
        }

        [HttpPost]
        public ActionResult SelectProducts(PurchasingCalculatorInputModel inputModel)
        {
            var criteria = TempData["currentCriteria"] as PurchasingCalculatorCriteriaModel;
            var productsWithAmount = new List<PurchasingCalculatorProductModel>();

            foreach (var selectedProductValue in inputModel.SelectedProductsValues)
            {
                Product product = unitOfWork.ProductRepository.GetById(selectedProductValue.SelectedProductId);
                productsWithAmount.Add(new PurchasingCalculatorProductModel(product, selectedProductValue.SelectedAmount));
            }

            if (ValidateSelectingProducts(inputModel, criteria.AmountOfProductFields))
            {
                var matchingProductOccurences = MatchProductOccurences(criteria);
                if (Request.Form["submitButtonShoppingBasket"] != null)
                    return View("CountShoppingBasket",
                        CountShoppingBasket(productsWithAmount, matchingProductOccurences));

                if (Request.Form["submitButtonInflation"] != null)
                    return View("CountInflation", CountInflation(productsWithAmount, matchingProductOccurences));

                if (Request.Form["submitButtonPurchasingPower"] != null)
                    return View("CountPurchasingPower",
                        CountPurchasingPower(productsWithAmount, matchingProductOccurences));
                return RedirectToAction("Index", "Home");
            }
            return View("ErrorCriteria");
        }

        public bool ValidateSelectingProducts(PurchasingCalculatorInputModel inputModel, int? amountOfProductFields)
        {
            for (var i=0; i<amountOfProductFields; i++)
            {
                if (inputModel.SelectedProductsValues[i].SelectedProductId == 0) return false;
            }
            return true;
        }

        public InflationModel CountInflation(IList<PurchasingCalculatorProductModel> products,
            List<ProductOccurence> matchingProductOccurences)
        {
            var shopInflation = CountInflationByShop(products, matchingProductOccurences);
            var productInflation = CountInflationByProduct(products, matchingProductOccurences);
            var averageInflation = CountInflationByProduct(products, matchingProductOccurences).Average(x => x.Inflation);
            return new InflationModel(shopInflation, productInflation, averageInflation);
        }

        public List<ShoppingBasketModel> CountShoppingBasket(IList<PurchasingCalculatorProductModel> products,
            List<ProductOccurence> matchingProductOccurences)
        {
            var shopsToCompare = SelectShopsToCompare(matchingProductOccurences);
            var shopsWithIncompleteBasket = 0;
            foreach (var shop in shopsToCompare)
            {
                decimal? counter = 0.00M;
                foreach (var product in products)
                {
                    var newestProductOccurence = FindNewestProductOccurence(matchingProductOccurences, shop, product);   
                    if (newestProductOccurence != null) counter = counter + (newestProductOccurence.ProductPrice * product.Amount);
                    else shop.ProductNotFound = true;
                }
                shop.BasketPrice = counter;
                if (shop.ProductNotFound) shopsWithIncompleteBasket++;
            }
            var results = shopsToCompare.Where(x => x.ProductNotFound == false).OrderBy(x => x.BasketPrice).ToList();
            if (shopsWithIncompleteBasket >= shopsToCompare.Count)
                ViewBag.BasketNotCompleteInAnyShop = true;
            else InitializeShoppingBasketChart(results);
            return results;
        }

        public List<InflationByShopModel> CountInflationByShop(IList<PurchasingCalculatorProductModel> products,
            List<ProductOccurence> matchingProductOccurences)
        {
            var shopsToConsider = SelectShopsToCompare(matchingProductOccurences);
            var shopInflations = new List<InflationByShopModel>();
            var shopsWithIncompleteBasket = 0;
            var isBasketComplete = true;

            foreach (var shop in shopsToConsider)
            {
                var productInflations = new List<decimal?>();
                foreach (var product in products)
                {
                    var newestProductOccurence = FindNewestProductOccurence(matchingProductOccurences, shop, product);
                    var oldestProductOccurence = FindOldestProductOccurence(matchingProductOccurences, shop, product);

                    if ((newestProductOccurence != null) && (oldestProductOccurence != null) && (newestProductOccurence != oldestProductOccurence))
                        productInflations.Add(CountInflationRate(newestProductOccurence, oldestProductOccurence));
                    else
                    {
                        shopsWithIncompleteBasket++;
                        isBasketComplete = false;
                        break;
                    }
                }
                if (isBasketComplete) shopInflations.Add(new InflationByShopModel(shop, productInflations.Average()));
            }
            if (shopsWithIncompleteBasket >= shopsToConsider.Count)
                ViewBag.BasketNotCompleteInAnyShop = true;
            else InitializeInflationByShopChart(shopInflations);
            return shopInflations.OrderBy(x => x.Inflation).ToList();
        }

        public List<InflationByProductModel> CountInflationByProduct(IList<PurchasingCalculatorProductModel> products,
            List<ProductOccurence> matchingProductOccurences)
        {
            var shopsToConsider = SelectShopsToCompare(matchingProductOccurences);
            var productInflations = new List<InflationByProductModel>();
            var productsNotFoundInShop = 0;
            var isBasketComplete = true;

            foreach (var product in products)
            {
                var shopInflations = new List<decimal?>();
                foreach (var shop in shopsToConsider)
                {
                    var newestProductOccurence = FindNewestProductOccurence(matchingProductOccurences, shop, product);
                    var oldestProductOccurence = FindOldestProductOccurence(matchingProductOccurences, shop, product);

                    if ((newestProductOccurence != null) && (oldestProductOccurence != null) && (newestProductOccurence != oldestProductOccurence))
                        shopInflations.Add(CountInflationRate(newestProductOccurence, oldestProductOccurence));
                    else
                    {
                        productsNotFoundInShop++;
                        isBasketComplete = false;
                        break;
                    }
                }
                if (isBasketComplete) productInflations.Add(new InflationByProductModel(product, shopInflations.Average()));
            }
            if (productsNotFoundInShop >= products.Count)
                ViewBag.NoProductFoundInAnyShop = true;
            else InitializeInflationByProductChart(productInflations);
            return productInflations.OrderBy(x => x.Inflation).ToList();
        }

        public List<PurchasingPowerModel> CountPurchasingPower(IList<PurchasingCalculatorProductModel> products,
            List<ProductOccurence> matchingProductOccurences)
        {
            var yearsToConsider = SelectYearsToCompare(matchingProductOccurences);
            var purchasingPowersAnnual = new List<PurchasingPowerModel>();

            foreach (var year in yearsToConsider)
            {
                var matchingProductOccurencesInYear = matchingProductOccurences.Where(x => x.ProductBuyDate.Year.Equals(year)).ToList();
                var shoppingBasketsInYear =
                    CountShoppingBasket(products, matchingProductOccurencesInYear);

                if (shoppingBasketsInYear.Any(x => x.BasketPrice > 0))
                {
                    var averageSalaryModel = new AverageSalaryModel(year);

BuySmart/Views/PurchasingCalculator/CountInflation.cshtml
@using Chart.Mvc.ComplexChart
@using Chart.Mvc.Extensions
@model BuySmart.ViewModels.PurchasingCalculator.InflationModel

<script src="@Url.Content("~/Scripts/Chart.js")"></script>

@{
    ViewBag.Title = "Oblicz inflację względem produktu";
}

<div class="content-section-a">
    <div class="container">
        <div class="row" align="center">
            @if (ViewBag.BasketNotCompleteInAnyShop == true)
            {
                @: Nie ma żadnego sklepu w danej lokalizacji, który zawierałby wszystkie produkty z zadanego asortymentu.
                }
            else
            {
                <h2>Wartość stopy inflacji względem sklepu (w stosunku rocznym)</h2><br /><br />
                <table>
                    <tr>
                        <td style="text-align: center; vertical-align: top;">
                            <h3>Średnia roczna inflacja względem poszczególnych sklepów:</h3> <br />
                            @foreach (var item in Model.ShopInflation)
                            {
                                if (item.Shop.Shop.Photo != null)
                                {
                                    string imageBase64 = Convert.ToBase64String(item.Shop.Shop.Photo.Content);
                                    string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                    <img src="@imageSrc" width="150" />
                                }
                                else
                                {
                                    <p>Brak zdjęcia</p>
                                }
                                <span style="font-weight: bold; font-size: 22px; padding-left: 24px;">@Html.DisplayFor(modelItem => item.Inflation) % </span><br /><br />
                            }
                        </td>
                        <td width="150"></td>
                        <td style="text-align: center; vertical-align: top;">
                            <h3>Inflacja względem poszczególnych sklepów w stosunku rocznym (w %)</h3>
                            @{
                                var barChartInflationByShop = new BarChart();
                                var shopLabels = ViewBag.ShopLabels;
                                var shopInflationValues = ViewBag.ShopInflationValues;

                                barChartInflationByShop.ComplexData.Labels.AddRange(shopLabels);
                                barChartInflationByShop.ComplexData.Datasets.AddRange(new List<ComplexDataset> {
                                    new ComplexDataset
                                    {
                                        Data = shopInflationValues,
                                        Label = "My First dataset",
                                        FillColor = "rgba(0, 174, 255, 0.9)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                                });
                            }
                            <canvas id="myCanvasInflationByShop" width="500" height="300"></canvas>
                            @Html.CreateChart("myCanvasInflationByShop", barChartInflationByShop)<br /><br />
                        </td>
                    </tr>
                </table>

                                }
            @if (ViewBag.NoProductFoundInAnyShop == true)
            {
                @: Nie ma takiego produktu, który byłby znaleziony w którymkolwiek sklepie w danej lokalizacji.
            }
            else
            {
                <br /><br/>
                <h2>Wartość stopy inflacji względem produktu (w stosunku rocznym)</h2><br /><br />
                <table>
                    <tr>
                        <td style="text-align: center; vertical-align: top;">
                            <h3>Średnia roczna inflacja względem poszczególnych produktów:</h3> <br />
                            @foreach (var item in Model.ProductInflation)
                            {
                                if (item.Product.Product.Photo != null)
                                {
                                    string imageBase64 = Convert.ToBase64String(item.Product.Product.Photo.Content);
                                    string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                    <img src="@imageSrc" width="150" />
                                }
                                else
                                {
                                    <p>Brak zdjęcia</p>
                                }
                                <span style="font-weight: bold; font-size: 22px; padding-left: 24px;">@Html.DisplayFor(modelItem => item.Product.Product.ProductDescription)</span>
                                <span style="font-weight: bold; font-size: 22px; padding-left: 24px;">@Html.DisplayFor(modelItem => item.Inflation) % </span><br /><br />
                            }
                        </td>
                        <td width="150"></td>
                        <td style="text-align: center; vertical-align: top;">
                            <h3>Inflacja względem poszczególnych produktów w stosunku rocznym (w %)</h3>
                            @{
                                var barChartInflationByProduct = new BarChart();
                                var productLabels = ViewBag.ProductLabels;
                                var productInflationValues = ViewBag.ProductInflationValues;

                                barChartInflationByProduct.ComplexData.Labels.AddRange(productLabels);
                                barChartInflationByProduct.ComplexData.Datasets.AddRange(new List<ComplexDataset> {
                                    new ComplexDataset
                                    {
                                        Data = productInflationValues,
                                        Label = "My First dataset",
                                        FillColor = "rgba(0, 174, 255, 0.9)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                                });
                            }
                            <canvas id="myCanvasInflationByProduct" width="500" height="300"></canvas>
                            @Html.CreateChart("myCanvasInflationByProduct", barChartInflationByProduct)<br /><br />
                        </td>
                    </tr>
                </table>


                <br/>
                <div align="center">

                    <br /><br />
                    <h2>Średnia wartość stopy inflacji w stosunku rocznym: @String.Format("{0:0.00}", Model.AverageInflation) %</h2>

                </div>

                                }

            <div align="center">
                <br />
                @Html.ActionLink("Powrót do kalkulatora zakupowego", "SelectCriteria", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

BuySmart/Views/PurchasingCalculator/CountPurchasingPower.cshtml
@using Chart.Mvc.ComplexChart
@using Chart.Mvc.Extensions
@model List<BuySmart.ViewModels.PurchasingCalculator.PurchasingPowerModel>

<script src="@Url.Content("~/Scripts/Chart.js")"></script>

@{
    ViewBag.Title = "Oblicz wartość siły nabywczej";
}

<div class="content-section-a">
    <div class="container">
        <div class="row" align="center">
            <h2>Siła nabywcza konsumentów w poszczególnych latach</h2>
            <h4>Ile zadanych koszyków zakupów można było średnio kupić w poszczególnych latach</h4>
            
            <table>
                <tr>
                    <td>
                        @foreach (var item in Model)
                        {
                            <h3>@Html.DisplayFor(modelItem => item.AverageSalaryModel.Year):
                            @String.Format("{0:0.00}", item.PurchasingPowerValue)</h3><br/><br/>
                        }
                    </td>
                    <td width="150">
                        
                    </td>
                    <td>
                        @{
                            var barChart = new BarChart();
                            var labels = ViewBag.Years;
                            var values = ViewBag.PurchasingPowerValues;

                            barChart.ComplexData.Labels.AddRange(labels);
                            barChart.ChartConfiguration.ScaleBeginAtZero = true;
                            barChart.ChartConfiguration.BarShowStroke = true;
                            barChart.ComplexData.Datasets.AddRange(new List<ComplexDataset>
                                {
                                    new ComplexDataset
                                    {
                                        Data = values,
                                        Label = "My First dataset",
                                        FillColor = "rgba(0, 174, 255, 0.9)",
                                        StrokeColor = "rgba(220,220,220,1)",
                                        PointColor = "rgba(220,220,220,1)",
                                        PointStrokeColor = "#fff",
                                        PointHighlightFill = "#fff",
                                        PointHighlightStroke = "rgba(220,220,220,1)",
                                    }
                                });
                        }
                        <canvas id="myCanvas" width="500" height="300"></canvas>
                        @Html.CreateChart("myCanvas", barChart)
                    </td>
                </tr>
            </table>
           
            <div align="center">
                <br/>
                @Html.ActionLink("Powrót do kalkulatora zakupowego", "SelectCriteria", null, new {@class = "btn btn-default"})
            </div>
        </div>
    </div>
</div>

BuySmart/Views/PurchasingCalculator/ErrorCriteria.cshtml
@model BuySmart.ViewModels.PurchasingCalculator.PurchasingCalculatorCriteriaModel

@{
    ViewBag.Title = "Błąd";
}


<div class="content-section-a">
    <div class="container">
        <div class="row">
            <h2>Błąd - proszę podać poprawnie wszystkie kryteria!</h2>

            @Html.ActionLink("Powrót", "SelectCriteria")
        </div>
    </div>
</div>

BuySmart/Views/PurchasingCalculator/SelectCriteria.cshtml
@model BuySmart.ViewModels.PurchasingCalculator.PurchasingCalculatorCriteriaModel

<link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-3.1.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/DatePicker/DatePicker.js")"></script>

@{
    ViewBag.Title = "Kalkulator zakupowy - podanie kryteriów";
}


<div class="content-section-a">
    <div class="container">
        <div class="row">
            @using (Html.BeginForm("SelectCriteria", "PurchasingCalculator", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h2>Podaj kryteria: </h2>
                    <hr/>
                    <div class="form-group">
                        @Html.Label("Ile produktów chcesz uwzględnić w obliczeniach?")
                        <div>
                            @Html.DropDownListFor(model => model.AmountOfProductFields, Enumerable.Range(1, 10).Select(i => new SelectListItem {Text = i.ToString(), Value = i.ToString()}),
                                new {htmlAttributes = new {@class = "form-control"}})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Lokalizacja (miasto)")
                        <div>
                            @Html.EditorFor(model => model.Localization, new {htmlAttributes = new {@class = "form-control"}})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Data od")
                        <div>
                            @Html.EditorFor(model => model.DateFrom, new {htmlAttributes = new {@class = "form-control date-picker"}})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Data do")
                        <div>
                            @Html.EditorFor(model => model.DateTo, new {htmlAttributes = new {@class = "form-control date-picker"}})
                        </div>
                    </div>

                    <div class="form-group">
                        <div>
                            <input type="submit" value="Następny krok: Wybór produktów" class="btn btn-default"/>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BuySmart/Views/PurchasingCalculator/SelectProducts.cshtml
@model BuySmart.ViewModels.PurchasingCalculator.PurchasingCalculatorInputModel

@{
    ViewBag.Title = "Kalkulator zakupowy - wybór produktów";
}

<div class="content-section-a">
    <div class="container">
        <div class="row">
            @using (Html.BeginForm("SelectProducts", "PurchasingCalculator", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h2>Wybierz produkty: </h2>
                    <hr />
                    @Html.Label("Ilość równa 0, jeśli zostawisz puste")
                    @for(var i=0; i < Model.Criteria.AmountOfProductFields; i++)
                    {
                        <div class="form-group">
                            <div>

                                @Html.Label("Produkt") @i:
                                @Html.DropDownListFor(model => model.SelectedProductsValues[i].SelectedProductId, Model.AllProducts, "---SELECT---", new {htmlAttributes = new {@class = "form-control"}})
                                @Html.Label("Ilość")
                                @Html.TextBoxFor(model => model.SelectedProductsValues[i].SelectedAmount, new {htmlAttributes = new {@class = "form-control"}})
                            </div>
                        </div>
                    }
                    <div class="form-group">
                        <div>
                            <input type="submit" name="submitButtonShoppingBasket" value="Oblicz koszt koszyka zakupów" class="btn btn-default" />
                            <input type="submit" name="submitButtonInflation" value="Oblicz inflację"  class="btn btn-default" />
                            <input type="submit" name="submitButtonPurchasingPower" value="Oblicz siłę nabywczą" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>